export const productCatalog = {
  meta: {
    currency: "USD",
    source: "Official Apple U.S. pricing",
    updatedAt: "2026-04-02",
  },
  sections: {
    newArrivals: [
      {
        id: "iphone-17-pro",
        name: "iPhone 17 Pro",
        price: "From $1,099",
        href: "https://www.apple.com/shop/buy-iphone/iphone-17-pro",
        src: "/heroes/iphone-17-pro.png",
        alt: "iPhone 17 Pro",
        width: 666,
        height: 500,
        imageClassName: "max-w-[178px] sm:max-w-[188px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "apple-watch-series-11",
        name: "Apple Watch Series 11",
        price: "From $399",
        href: "https://www.apple.com/shop/buy-watch",
        src: "/categories/apple-watch.avif",
        alt: "Apple Watch Series 11",
        width: 72,
        height: 72,
        imageClassName: "max-w-[92px] scale-[2.05] sm:max-w-[96px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "airpods-pro-3",
        name: "AirPods Pro 3",
        price: "$249",
        href: "https://www.apple.com/shop/buy-airpods/airpods-pro-3",
        src: "/categories/airpods.avif",
        alt: "AirPods Pro 3",
        width: 72,
        height: 72,
        imageClassName: "max-w-[94px] scale-[2.05] sm:max-w-[98px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "ipad-air-m4",
        name: "iPad Air (M4)",
        price: "From $599",
        href: "https://www.apple.com/shop/buy-ipad/ipad-air",
        src: "/categories/ipad.avif",
        alt: "iPad Air with M4",
        width: 78,
        height: 72,
        imageClassName: "max-w-[110px] scale-[2.05] sm:max-w-[116px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "macbook-pro",
        name: "MacBook Pro",
        price: "From $1,699",
        href: "https://www.apple.com/shop/buy-mac/macbook-pro",
        src: "/categories/macbook.avif",
        alt: "MacBook Pro",
        width: 84,
        height: 72,
        imageClassName: "max-w-[118px] scale-[2] sm:max-w-[126px]",
        panelClassName: "bg-[#f7f7f8]",
      },
    ],
    bestSellers: [
      {
        id: "iphone-17",
        name: "iPhone 17",
        price: "From $799",
        href: "https://www.apple.com/shop/buy-iphone",
        src: "/categories/iphone.avif",
        alt: "iPhone 17",
        width: 72,
        height: 72,
        imageClassName: "max-w-[98px] scale-[2.12] sm:max-w-[102px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "apple-watch-se-3",
        name: "Apple Watch SE 3",
        price: "From $249",
        href: "https://www.apple.com/shop/buy-watch",
        src: "/categories/apple-watch.avif",
        alt: "Apple Watch SE 3",
        width: 72,
        height: 72,
        imageClassName: "max-w-[92px] scale-[2.05] sm:max-w-[96px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "airpods-4",
        name: "AirPods 4",
        price: "$129",
        href: "https://www.apple.com/airpods/",
        src: "/categories/airpods.avif",
        alt: "AirPods 4",
        width: 72,
        height: 72,
        imageClassName: "max-w-[94px] scale-[2.05] sm:max-w-[98px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "ipad-air-m4-best-seller",
        name: "iPad Air (M4)",
        price: "From $599",
        href: "https://www.apple.com/shop/buy-ipad/ipad-air",
        src: "/categories/ipad.avif",
        alt: "iPad Air with M4",
        width: 78,
        height: 72,
        imageClassName: "max-w-[110px] scale-[2.05] sm:max-w-[116px]",
        panelClassName: "bg-[#f7f7f8]",
      },
      {
        id: "macbook-air-m5",
        name: "MacBook Air (M5)",
        price: "From $1,099",
        href: "https://www.apple.com/shop/buy-mac",
        src: "/categories/macbook.avif",
        alt: "MacBook Air with M5",
        width: 84,
        height: 72,
        imageClassName: "max-w-[118px] scale-[2] sm:max-w-[126px]",
        panelClassName: "bg-[#f7f7f8]",
      },
    ],
  },
};
